### ISSUE TITLE
Blaze integration

### ISSUE THREAD

**Issue by elie222** [Differential/meteor-profile#13]
While building package `profile`:
client/views/profile.html:8: Expected "div" end tag
...="{{email}}"></input>             <span c...

**Comment by elie222** [comment]
Removing the </input> tags will fix it.

**Comment by niemilkm** [comment]
I have this same issue - what tags were removed to resolve this issue?

Thanks!

**Comment by schnie** [comment]
I think the closing input tags just need to be removed,  since input tags do not need to be closed.

I have this fixed locally and am planning to update 3 or 4 of our other packages as well.

**Comment by ryw** [comment]
Should be fixed in master branch, will release today.
