### ISSUE TITLE
Error while building package 

### ISSUE THREAD

**Issue by isAlmogK** [Differential/meteor-profile#17]
Just tried installing and I get the following error message 

While building package `profile`:
client/views/profile.html:8: Expected "div" end tag
...="{{email}}"></input>             <span c...
                        ^

**Comment by ryw** [comment]
Fixed in master, change your `smart.json`:

```
"profile": {
  "git": "https://github.com/Differential/meteor-profile.git"
}
```

**Comment by isAlmogK** [comment]
Thanks this is fixed, but getting a different error now and the docs are really bad.
