### ISSUE TITLE
Style userCard preview to use icons for url, googlePlusUrl, twitterHandle

### ISSUE THREAD

**Issue by ryw** [Differential/meteor-profile#2]

**Comment by dapearce** [comment]
Should we have a preview in the package? Seems to me many sites won't need a profile preview. Only sites where the provile is actually public is it useful, and I could argue it's not required there (you can't preview profiles on Facebook, LinkedIn, twitter, etc)

—

**Comment by ryw** [comment]
Im thinking the preview helps verify they entered what they think they entered - ie. test the twitter link, etc.

Also, it provides a sample implementation for building a profile view.

We could create a configuration option to suppress the preview, or to substitute in their own view for the preview in case  they want to show how the preview actually appears on their site.
