### ISSUE TITLE
Build form via configuration rather than hardcoded field names

### ISSUE THREAD

**Issue by ryw** [Differential/meteor-profile#3]

**Comment by chmac** [comment]
Any suggestions on how to do go about this? I'm open to submitting a pull request, but not sure what the most elegant approach is, I'm new to meteor.

**Comment by queso** [comment]
@ryw do you want me to take a stab at this with bedifferential/simple-form?

**Comment by ryw** [comment]
@queso heck yeah!

**Comment by queso** [comment]
Ok, I took a stab with #19 :)

**Comment by queso** [comment]
This is fixed in master and will be in the next release.
